CREATE TABLE IF NOT EXISTS "boosts" (
	"id" INTEGER NOT NULL UNIQUE,
	"user_id" INTEGER NOT NULL,
	"chat_id" INTEGER NOT NULL,
	"item_id" INTEGER NOT NULL,
	"boost_type" TEXT NOT NULL,
	"purchased_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"expires_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (item_id) REFERENCES shop(id),
	PRIMARY KEY("id")
);
