package main

// Error messages separated for easy modification
const (
	ErrStatsNotFound           = "**No statistics available for this user.**"
	ErrNoRankingsAvailable     = "**Rankings are not available yet! Engage more to earn points.**"
	ErrHistoryUnavailable      = "**No history found for the specified user.**"
	ErrInvalidPointsAmount     = "The point amount must be a positive number."
	ErrInvalidUserID           = "The provided user ID format is invalid."
	ErrItemNotFound            = "**No item found with the specified ID.**"
	ErrSelfGift                = "You cannot send a gift to yourself!"
	ErrBotGift                 = "Gifting to the bot is not allowed."
	ErrZeroGiftAmount          = "The gift amount must be greater than zero."
	ErrInsufficientPoints      = "**You don’t have enough points to send a gift!**"
	ErrNotEnoughPoints         = "Insufficient points."
	ErrUserInsufficientPoints  = "User doesn't have enough points."
	ErrUserNotFound            = "The specified user does not exist."
	ErrGiftProcessing          = "An error occurred while processing the gift. Please try again later."
	ErrBoostUnavailable        = "**No active boosts available!**"
	ErrShopEmpty               = "**The shop is currently empty. Please check back later!**"
	ErrNoPointsEarned          = "**You haven’t earned any points yet! Start engaging to earn some.**"
	ErrInsufficientBalance     = "**You don’t have enough points! Keep engaging to earn more.**"
	ErrItemPurchaseFailed      = "**Unable to complete the purchase of the item.**"
	ErrSeizeFailed             = "**Failed to seize the item or points.**"
	ErrInvalidSeizeAmount      = "**Seize amount invalid!**"
	ErrUpdateUserFailed        = "Failed to update user details."
	ErrAddPointsFailed         = "Failed to add points to the database."
	ErrUnknownError            = "**An unexpected error occurred. Please contact support if this persists.**"
	ErrCannotDeductOwnPoints   = "You cannot deduct points from yourself."
	ErrCannotDeductAdminPoints = "You cannot deduct points from another administrator."
)
